[server]
maxUploadSize = 1000
maxMessageSize = 1000

[theme]
primaryColor = "#000000"  # Black for buttons, sliders, etc.
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray sidebar
textColor = "#000000"  # Black text
font = "sans serif"
